// Copyright 2026 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *AllowedHost) DeepCopyInto(out *AllowedHost) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of AllowedHost.
func (in *AllowedHost) DeepCopy() *AllowedHost {
	if in == nil {
		return nil
	}
	out := new(AllowedHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *AllowedMCPServer) DeepCopyInto(out *AllowedMCPServer) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of AllowedMCPServer.
func (in *AllowedMCPServer) DeepCopy() *AllowedMCPServer {
	if in == nil {
		return nil
	}
	out := new(AllowedMCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *AuditSpec) DeepCopyInto(out *AuditSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of AuditSpec.
func (in *AuditSpec) DeepCopy() *AuditSpec {
	if in == nil {
		return nil
	}
	out := new(AuditSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OperationsSpec) DeepCopyInto(out *OperationsSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of OperationsSpec.
func (in *OperationsSpec) DeepCopy() *OperationsSpec {
	if in == nil {
		return nil
	}
	out := new(OperationsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SandboxPolicy) DeepCopyInto(out *SandboxPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of SandboxPolicy.
func (in *SandboxPolicy) DeepCopy() *SandboxPolicy {
	if in == nil {
		return nil
	}
	out := new(SandboxPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *SandboxPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SandboxPolicyList) DeepCopyInto(out *SandboxPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of SandboxPolicyList.
func (in *SandboxPolicyList) DeepCopy() *SandboxPolicyList {
	if in == nil {
		return nil
	}
	out := new(SandboxPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *SandboxPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SandboxPolicySpec) DeepCopyInto(out *SandboxPolicySpec) {
	*out = *in
	if in.AllowedHosts != nil {
		in, out := &in.AllowedHosts, &out.AllowedHosts
		*out = make([]AllowedHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowedMCPServers != nil {
		in, out := &in.AllowedMCPServers, &out.AllowedMCPServers
		*out = make([]AllowedMCPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TokenLimits != nil {
		in, out := &in.TokenLimits, &out.TokenLimits
		*out = new(TokenLimitsSpec)
		**out = **in
	}
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = new(OperationsSpec)
		**out = **in
	}
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = new(AuditSpec)
		**out = **in
	}
	if in.ToolAccess != nil {
		in, out := &in.ToolAccess, &out.ToolAccess
		*out = new(ToolAccessSpec)
		**out = **in
	}
}

// DeepCopy creates a deep copy of SandboxPolicySpec.
func (in *SandboxPolicySpec) DeepCopy() *SandboxPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SandboxPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SandboxPolicyStatus) DeepCopyInto(out *SandboxPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of SandboxPolicyStatus.
func (in *SandboxPolicyStatus) DeepCopy() *SandboxPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *TokenLimitsSpec) DeepCopyInto(out *TokenLimitsSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of TokenLimitsSpec.
func (in *TokenLimitsSpec) DeepCopy() *TokenLimitsSpec {
	if in == nil {
		return nil
	}
	out := new(TokenLimitsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ToolAccessSpec) DeepCopyInto(out *ToolAccessSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of ToolAccessSpec.
func (in *ToolAccessSpec) DeepCopy() *ToolAccessSpec {
	if in == nil {
		return nil
	}
	out := new(ToolAccessSpec)
	in.DeepCopyInto(out)
	return out
}
